name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Build
      run: go build -v 
      
    - name: Build Sample
      run: go build sample/simple_market/simple_market.go
